# Generated by Django 5.1.1 on 2024-09-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('response_time', models.CharField(max_length=100)),
                ('response_rate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('start_date_availability', models.DateTimeField()),
                ('end_date_availability', models.DateTimeField()),
                ('stars', models.FloatField(default=0.0)),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('is_published', models.BooleanField(default=True)),
                ('guests', models.IntegerField(default=1)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.host')),
            ],
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stars', models.FloatField(default=0.0)),
                ('review', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listing')),
            ],
        ),
    ]
